name: maxvit_512
savepath: v3
epoches: 150
strategy: ddp
accumulate_batches: 1
precision: 16
gradient_clip_val: 5.0
data_config:
  batch_size: 24
  val_batch_size: 64
  dataroot: /neodata/pathology_breast/aidea/dataset/
  datalist: /neodata/pathology_breast/aidea/crop_code/datalist/fold_0.json
  cache: false
  transforms_config:
    img_size: 512
    random_transform: true
    random_rotation: false
model_config:
  model:
    num_classes: 33
    backbone: maxvit_512
    backbone_num_features: 1000
  loss: FL
  use_additional_loss: false
  optimizer: adamw
  lr: 5.0e-05
  scheduler:
    name: cosine
    T_max: 50
    eta_min: 0
ckpt: ../checkpoint/v3/maxvit_512/f1.ckpt
acc:
  val_acc: 0.843086888541434
  test_acc: 0.8385835567470956
f1:
  val_f1: 0.8406554587691072
  test_f1: 0.8367989098521789
