name: swin_s_largebs
savepath: v1
epoches: 100
strategy: ddp
accumulate_batches: 8
precision: 16
data_config:
  batch_size: 64
  val_batch_size: 128
  dataroot: /neodata/pathology_breast/aidea/dataset/
  datalist: /neodata/pathology_breast/aidea/crop_code/datalist/fold_0.json
  cache: false
  transforms_config:
    img_size: 512
    random_transform: false
model_config:
  model:
    num_classes: 33
    backbone: swin_s
    backbone_num_features: 1000
  loss: FL
  optimizer: adamw
  lr: 0.0001
ckpt: ../checkpoint/v1/swin_s_largebs/acc.ckpt
acc:
  val_acc: 0.8758096939915122
  test_acc: 0.8790214477211796
