name: swin_v2_t_1080
savepath: v3
epoches: 50
strategy: ddp
accumulate_batches: 2
precision: 16
gradient_clip_val: 5.0
data_config:
  batch_size: 16
  val_batch_size: 64
  dataroot: /neodata/pathology_breast/aidea/dataset/
  datalist: /neodata/pathology_breast/aidea/crop_code/datalist/fold_0.json
  cache: false
  transforms_config:
    img_size: 1080
    random_transform: false
    random_rotation: false
model_config:
  model:
    num_classes: 33
    backbone: swin_v2_t
    backbone_num_features: 1000
  loss: FL
  use_additional_loss: false
  optimizer: adamw
  lr: 0.0001
  scheduler:
    name: cosine
    T_max: 50
    eta_min: 0
ckpt: ../checkpoint/v3/swin_v2_t_1080/f1.ckpt
