name: test
savepath: v1
epoches: 1
strategy: ddp
accumulate_batches: 2
precision: 16
data_config:
  batch_size: 256
  val_batch_size: 256
  dataroot: /neodata/pathology_breast/aidea/dataset/
  datalist: /neodata/pathology_breast/aidea/crop_code/datalist/fold_0.json
  cache: false
  transforms_config:
    img_size: 224
    random_transform: false
model_config:
  model:
    num_classes: 33
    backbone: swin_s
    backbone_num_features: 1000
  loss: FL
  optimizer: adamw
  lr: 0.0001
ckpt: ../checkpoint/v1/test/acc.ckpt
